//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagnoMedia.Web.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class appbrowservalidity
    {
        public int ThirdPartyApplicationId { get; set; }
        public int BrowserId { get; set; }
        public int Order { get; set; }
    }
}
