//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagnoMedia.Web.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class magnomediaEntities : DbContext
    {
        public magnomediaEntities()
            : base("name=magnomediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appbrowservalidity> appbrowservalidities { get; set; }
        public virtual DbSet<appcountryvalidity> appcountryvalidities { get; set; }
        public virtual DbSet<browser> browsers { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<installationreport> installationreports { get; set; }
        public virtual DbSet<thirdpartyapplication> thirdpartyapplications { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userinstalldetail> userinstalldetails { get; set; }
        public virtual DbSet<userinstallerror> userinstallerrors { get; set; }
    }
}
