//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagnoMedia.Web.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class thirdpartyapplication
    {
        public string Name { get; set; }
        public string Url { get; set; }
        public short HasUrl { get; set; }
        public string InstallerName { get; set; }
        public string DownloadUrl { get; set; }
        public string Arguments { get; set; }
        public string RegistoryCheck { get; set; }
        public int Id { get; set; }
    }
}
