//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagnoMedia.Web.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string FingerPrint { get; set; }
        public string OSName { get; set; }
        public string BrowserName { get; set; }
        public string CountryName { get; set; }
        public string IP { get; set; }
        public int RefererId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Id { get; set; }
    }
}
