//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidSoom {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidSoom.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string frmConfiguracion_btnCancel {
            get {
                return ResourceManager.GetString("frmConfiguracion_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        internal static string frmConfiguracion_btnOK {
            get {
                return ResourceManager.GetString("frmConfiguracion_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify updates automatically.
        /// </summary>
        internal static string frmConfiguracion_cUpdates {
            get {
                return ResourceManager.GetString("frmConfiguracion_cUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Speed (kb/s): .
        /// </summary>
        internal static string frmConfiguracion_cVelocidad {
            get {
                return ResourceManager.GetString("frmConfiguracion_cVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string frmConfiguracion_frmConfiguracion {
            get {
                return ResourceManager.GetString("frmConfiguracion_frmConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max simultaneos downloads:.
        /// </summary>
        internal static string frmConfiguracion_lblDescargas {
            get {
                return ResourceManager.GetString("frmConfiguracion_lblDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language:.
        /// </summary>
        internal static string frmConfiguracion_lblIdioma {
            get {
                return ResourceManager.GetString("frmConfiguracion_lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloads path: .
        /// </summary>
        internal static string frmConfiguracion_lblRuta {
            get {
                return ResourceManager.GetString("frmConfiguracion_lblRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloads.
        /// </summary>
        internal static string frmConfiguracion_tDescargas {
            get {
                return ResourceManager.GetString("frmConfiguracion_tDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        internal static string frmConfiguracion_tGeneral {
            get {
                return ResourceManager.GetString("frmConfiguracion_tGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar e Instalar.
        /// </summary>
        internal static string frmInstall_btnAceptar {
            get {
                return ResourceManager.GetString("frmInstall_btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cancelar.
        /// </summary>
        internal static string frmInstall_btnCancelar {
            get {
                return ResourceManager.GetString("frmInstall_btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea un acceso directo en el escritorio..
        /// </summary>
        internal static string frmInstall_cAcceso {
            get {
                return ResourceManager.GetString("frmInstall_cAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Define y mantiene Vidsoom.com como mi página de inicio y como motor de búsqueda predeterminado..
        /// </summary>
        internal static string frmInstall_cInicio {
            get {
                return ResourceManager.GetString("frmInstall_cInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalación de VidSoom.
        /// </summary>
        internal static string frmInstall_frmInstall {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de instalación.
        /// </summary>
        internal static string frmInstall_gTipo {
            get {
                return ResourceManager.GetString("frmInstall_gTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acuerdo de licencia.
        /// </summary>
        internal static string frmInstall_lblAcuerdo {
            get {
                return ResourceManager.GetString("frmInstall_lblAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el idioma del programa de instalación:.
        /// </summary>
        internal static string frmInstall_lblIdioma {
            get {
                return ResourceManager.GetString("frmInstall_lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al hacer click en &quot;Aceptar e instalar&quot; usted está aceptando el acuerdo de licencia..
        /// </summary>
        internal static string frmInstall_lblLeyenda {
            get {
                return ResourceManager.GetString("frmInstall_lblLeyenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Define y mantiene Vidsoom.com como mi página de inicio y como motor de búsqueda predeterminado.
        ///• Crea un acceso directo en el escritorio..
        /// </summary>
        internal static string frmInstall_lblTipica {
            get {
                return ResourceManager.GetString("frmInstall_lblTipica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalación personalizada.
        /// </summary>
        internal static string frmInstall_oPersonalizada {
            get {
                return ResourceManager.GetString("frmInstall_oPersonalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalación típica (recomendada).
        /// </summary>
        internal static string frmInstall_oTipica {
            get {
                return ResourceManager.GetString("frmInstall_oTipica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files.
        /// </summary>
        internal static string frmMain_Archivos {
            get {
                return ResourceManager.GetString("frmMain_Archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string frmMain_btnConfiguracion {
            get {
                return ResourceManager.GetString("frmMain_btnConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        internal static string frmMain_btnDescargar {
            get {
                return ResourceManager.GetString("frmMain_btnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Downloads.
        /// </summary>
        internal static string frmMain_btnDescargas {
            get {
                return ResourceManager.GetString("frmMain_btnDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string frmMain_btnEliminar {
            get {
                return ResourceManager.GetString("frmMain_btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string frmMain_btnPausa {
            get {
                return ResourceManager.GetString("frmMain_btnPausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resume.
        /// </summary>
        internal static string frmMain_btnPausa_Continuar {
            get {
                return ResourceManager.GetString("frmMain_btnPausa_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste links.
        /// </summary>
        internal static string frmMain_btnPegar {
            get {
                return ResourceManager.GetString("frmMain_btnPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string frmMain_btnPrevisualizar {
            get {
                return ResourceManager.GetString("frmMain_btnPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open directory.
        /// </summary>
        internal static string frmMain_cmAbrir {
            get {
                return ResourceManager.GetString("frmMain_cmAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string frmMain_cmEliminar {
            get {
                return ResourceManager.GetString("frmMain_cmEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string frmMain_cmPausa {
            get {
                return ResourceManager.GetString("frmMain_cmPausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste links.
        /// </summary>
        internal static string frmMain_cmPegar {
            get {
                return ResourceManager.GetString("frmMain_cmPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string frmMain_cmPrevisualizar {
            get {
                return ResourceManager.GetString("frmMain_cmPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you really want to delete the selected downloads? Downloads not yet ended will be deleted from disk..
        /// </summary>
        internal static string frmMain_Confirm_Eliminar {
            get {
                return ResourceManager.GetString("frmMain_Confirm_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloaded.
        /// </summary>
        internal static string frmMain_Descargado {
            get {
                return ResourceManager.GetString("frmMain_Descargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading.
        /// </summary>
        internal static string frmMain_Descargando {
            get {
                return ResourceManager.GetString("frmMain_Descargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloads.
        /// </summary>
        internal static string frmMain_Descargas {
            get {
                return ResourceManager.GetString("frmMain_Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents.
        /// </summary>
        internal static string frmMain_Documentos {
            get {
                return ResourceManager.GetString("frmMain_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string frmMain_Estado {
            get {
                return ResourceManager.GetString("frmMain_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open downloads folder.
        /// </summary>
        internal static string frmMain_mmAbrir {
            get {
                return ResourceManager.GetString("frmMain_mmAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About VidSoom.
        /// </summary>
        internal static string frmMain_mmAcerca {
            get {
                return ResourceManager.GetString("frmMain_mmAcerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string frmMain_mmArchivo {
            get {
                return ResourceManager.GetString("frmMain_mmArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string frmMain_mmAyuda {
            get {
                return ResourceManager.GetString("frmMain_mmAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string frmMain_mmConfiguracion {
            get {
                return ResourceManager.GetString("frmMain_mmConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string frmMain_mmEdicion {
            get {
                return ResourceManager.GetString("frmMain_mmEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string frmMain_mmEliminar {
            get {
                return ResourceManager.GetString("frmMain_mmEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause/Resume.
        /// </summary>
        internal static string frmMain_mmPausar {
            get {
                return ResourceManager.GetString("frmMain_mmPausar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste links.
        /// </summary>
        internal static string frmMain_mmPegar {
            get {
                return ResourceManager.GetString("frmMain_mmPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string frmMain_mmPrevisualizar {
            get {
                return ResourceManager.GetString("frmMain_mmPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string frmMain_mmSalir {
            get {
                return ResourceManager.GetString("frmMain_mmSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The protocol of the URL is invalid..
        /// </summary>
        internal static string frmMain_msgBadProtocol {
            get {
                return ResourceManager.GetString("frmMain_msgBadProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a new version of VidSoom available! Do you want to download it now?.
        /// </summary>
        internal static string frmMain_msgNewVersion {
            get {
                return ResourceManager.GetString("frmMain_msgNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a new version of VidSoom available! Do you want to download it now?.
        /// </summary>
        internal static string frmMain_msgUpdate {
            get {
                return ResourceManager.GetString("frmMain_msgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music.
        /// </summary>
        internal static string frmMain_Musica {
            get {
                return ResourceManager.GetString("frmMain_Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source.
        /// </summary>
        internal static string frmMain_Origen {
            get {
                return ResourceManager.GetString("frmMain_Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string frmMain_Peso {
            get {
                return ResourceManager.GetString("frmMain_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programs.
        /// </summary>
        internal static string frmMain_Programas {
            get {
                return ResourceManager.GetString("frmMain_Programas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progress.
        /// </summary>
        internal static string frmMain_Progreso {
            get {
                return ResourceManager.GetString("frmMain_Progreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading: .
        /// </summary>
        internal static string frmMain_sDescargando {
            get {
                return ResourceManager.GetString("frmMain_sDescargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Session time: .
        /// </summary>
        internal static string frmMain_sTiempo {
            get {
                return ResourceManager.GetString("frmMain_sTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total speed: .
        /// </summary>
        internal static string frmMain_sVelocidad {
            get {
                return ResourceManager.GetString("frmMain_sVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string frmMain_Titulo {
            get {
                return ResourceManager.GetString("frmMain_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste here links to download....
        /// </summary>
        internal static string frmMain_tURL {
            get {
                return ResourceManager.GetString("frmMain_tURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed.
        /// </summary>
        internal static string frmMain_Velocidad {
            get {
                return ResourceManager.GetString("frmMain_Velocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos.
        /// </summary>
        internal static string frmMain_Videos {
            get {
                return ResourceManager.GetString("frmMain_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string frmQuality_btnCancelar {
            get {
                return ResourceManager.GetString("frmQuality_btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        internal static string frmQuality_btnDescargar {
            get {
                return ResourceManager.GetString("frmQuality_btnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select video quality and format.
        /// </summary>
        internal static string frmQuality_frmQuality {
            get {
                return ResourceManager.GetString("frmQuality_frmQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a quality.
        /// </summary>
        internal static string frmQuality_msgSeleccione {
            get {
                return ResourceManager.GetString("frmQuality_msgSeleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ended.
        /// </summary>
        internal static string General_Ended {
            get {
                return ResourceManager.GetString("General_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string General_EndedWithError {
            get {
                return ResourceManager.GetString("General_EndedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to prepare.
        /// </summary>
        internal static string General_NeedToPrepare {
            get {
                return ResourceManager.GetString("General_NeedToPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paused.
        /// </summary>
        internal static string General_Paused {
            get {
                return ResourceManager.GetString("General_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausing.
        /// </summary>
        internal static string General_Pausing {
            get {
                return ResourceManager.GetString("General_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prepared.
        /// </summary>
        internal static string General_Prepared {
            get {
                return ResourceManager.GetString("General_Prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparing.
        /// </summary>
        internal static string General_Preparing {
            get {
                return ResourceManager.GetString("General_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for reconnect.
        /// </summary>
        internal static string General_WaitingForReconnect {
            get {
                return ResourceManager.GetString("General_WaitingForReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading.
        /// </summary>
        internal static string General_Working {
            get {
                return ResourceManager.GetString("General_Working", resourceCulture);
            }
        }
    }
}
