//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidSoom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidSoom.English2", typeof(English2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept and Install.
        /// </summary>
        internal static string frmInstall_btnAceptar {
            get {
                return ResourceManager.GetString("frmInstall_btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string frmInstall_btnCancelar {
            get {
                return ResourceManager.GetString("frmInstall_btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a shortcut in your desktop.
        /// </summary>
        internal static string frmInstall_cAcceso {
            get {
                return ResourceManager.GetString("frmInstall_cAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define y mantiene Vidsoom.com como mi página de inicio y como motor de búsqueda predeterminado..
        /// </summary>
        internal static string frmInstall_cInicio {
            get {
                return ResourceManager.GetString("frmInstall_cInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VidSom Installation.
        /// </summary>
        internal static string frmInstall_frmInstall {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation type:.
        /// </summary>
        internal static string frmInstall_gTipo {
            get {
                return ResourceManager.GetString("frmInstall_gTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License agreement.
        /// </summary>
        internal static string frmInstall_lblAcuerdo {
            get {
                return ResourceManager.GetString("frmInstall_lblAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the installation program language:.
        /// </summary>
        internal static string frmInstall_lblIdioma {
            get {
                return ResourceManager.GetString("frmInstall_lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al hacer click en &quot;Aceptar e instalar&quot; usted está aceptando el acuerdo de licencia..
        /// </summary>
        internal static string frmInstall_lblLeyenda {
            get {
                return ResourceManager.GetString("frmInstall_lblLeyenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Define y mantiene Vidsoom.com como mi página de inicio y como motor de búsqueda predeterminado.
        ///• Crea un acceso directo en el escritorio..
        /// </summary>
        internal static string frmInstall_lblTipica {
            get {
                return ResourceManager.GetString("frmInstall_lblTipica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom installation.
        /// </summary>
        internal static string frmInstall_oPersonalizada {
            get {
                return ResourceManager.GetString("frmInstall_oPersonalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical installation (recommended).
        /// </summary>
        internal static string frmInstall_oTipica {
            get {
                return ResourceManager.GetString("frmInstall_oTipica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        internal static string frmMain_Archivos {
            get {
                return ResourceManager.GetString("frmMain_Archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string frmMain_btnConfiguracion {
            get {
                return ResourceManager.GetString("frmMain_btnConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string frmMain_btnDescargar {
            get {
                return ResourceManager.GetString("frmMain_btnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Descargas.
        /// </summary>
        internal static string frmMain_btnDescargas {
            get {
                return ResourceManager.GetString("frmMain_btnDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string frmMain_btnEliminar {
            get {
                return ResourceManager.GetString("frmMain_btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa.
        /// </summary>
        internal static string frmMain_btnPausa {
            get {
                return ResourceManager.GetString("frmMain_btnPausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar enlaces.
        /// </summary>
        internal static string frmMain_btnPegar {
            get {
                return ResourceManager.GetString("frmMain_btnPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargado.
        /// </summary>
        internal static string frmMain_Descargado {
            get {
                return ResourceManager.GetString("frmMain_Descargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando.
        /// </summary>
        internal static string frmMain_Descargando {
            get {
                return ResourceManager.GetString("frmMain_Descargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargas.
        /// </summary>
        internal static string frmMain_Descargas {
            get {
                return ResourceManager.GetString("frmMain_Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string frmMain_Documentos {
            get {
                return ResourceManager.GetString("frmMain_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string frmMain_Estado {
            get {
                return ResourceManager.GetString("frmMain_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string frmMain_mmArchivo {
            get {
                return ResourceManager.GetString("frmMain_mmArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        internal static string frmMain_mmAyuda {
            get {
                return ResourceManager.GetString("frmMain_mmAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        internal static string frmMain_mmHerramientas {
            get {
                return ResourceManager.GetString("frmMain_mmHerramientas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Música.
        /// </summary>
        internal static string frmMain_Musica {
            get {
                return ResourceManager.GetString("frmMain_Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        internal static string frmMain_Origen {
            get {
                return ResourceManager.GetString("frmMain_Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programas.
        /// </summary>
        internal static string frmMain_Programas {
            get {
                return ResourceManager.GetString("frmMain_Programas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progreso.
        /// </summary>
        internal static string frmMain_Progreso {
            get {
                return ResourceManager.GetString("frmMain_Progreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        internal static string frmMain_Tamaño {
            get {
                return ResourceManager.GetString("frmMain_Tamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        internal static string frmMain_Titulo {
            get {
                return ResourceManager.GetString("frmMain_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegue aquí los enlaces a descargar....
        /// </summary>
        internal static string frmMain_tURL {
            get {
                return ResourceManager.GetString("frmMain_tURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad.
        /// </summary>
        internal static string frmMain_Velocidad {
            get {
                return ResourceManager.GetString("frmMain_Velocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string frmMain_Videos {
            get {
                return ResourceManager.GetString("frmMain_Videos", resourceCulture);
            }
        }
    }
}
