//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidSoom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidSoom.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string frmConfiguracion_btnCancel {
            get {
                return ResourceManager.GetString("frmConfiguracion_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string frmConfiguracion_btnOK {
            get {
                return ResourceManager.GetString("frmConfiguracion_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar actualizaciones automáticamente.
        /// </summary>
        internal static string frmConfiguracion_cUpdates {
            get {
                return ResourceManager.GetString("frmConfiguracion_cUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad máxima (kb/s):.
        /// </summary>
        internal static string frmConfiguracion_cVelocidad {
            get {
                return ResourceManager.GetString("frmConfiguracion_cVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string frmConfiguracion_frmConfiguracion {
            get {
                return ResourceManager.GetString("frmConfiguracion_frmConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de descargas simultaneas:.
        /// </summary>
        internal static string frmConfiguracion_lblDescargas {
            get {
                return ResourceManager.GetString("frmConfiguracion_lblDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        internal static string frmConfiguracion_lblIdioma {
            get {
                return ResourceManager.GetString("frmConfiguracion_lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de descargas:.
        /// </summary>
        internal static string frmConfiguracion_lblRuta {
            get {
                return ResourceManager.GetString("frmConfiguracion_lblRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargas.
        /// </summary>
        internal static string frmConfiguracion_tDescargas {
            get {
                return ResourceManager.GetString("frmConfiguracion_tDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string frmConfiguracion_tGeneral {
            get {
                return ResourceManager.GetString("frmConfiguracion_tGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Aceptar e Instalar.
        /// </summary>
        internal static string frmInstall_btnAceptar {
            get {
                return ResourceManager.GetString("frmInstall_btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancelar.
        /// </summary>
        internal static string frmInstall_btnCancelar {
            get {
                return ResourceManager.GetString("frmInstall_btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea un acceso directo en el escritorio..
        /// </summary>
        internal static string frmInstall_cAcceso {
            get {
                return ResourceManager.GetString("frmInstall_cAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define y mantiene Vidsoom.com como mi página de inicio y como motor de búsqueda predeterminado..
        /// </summary>
        internal static string frmInstall_cInicio {
            get {
                return ResourceManager.GetString("frmInstall_cInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación de VidSoom.
        /// </summary>
        internal static string frmInstall_frmInstall {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de instalación.
        /// </summary>
        internal static string frmInstall_gTipo {
            get {
                return ResourceManager.GetString("frmInstall_gTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuerdo de licencia.
        /// </summary>
        internal static string frmInstall_lblAcuerdo {
            get {
                return ResourceManager.GetString("frmInstall_lblAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el idioma del programa de instalación:.
        /// </summary>
        internal static string frmInstall_lblIdioma {
            get {
                return ResourceManager.GetString("frmInstall_lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al hacer click en &quot;Aceptar e instalar&quot; usted está aceptando el acuerdo de licencia..
        /// </summary>
        internal static string frmInstall_lblLeyenda {
            get {
                return ResourceManager.GetString("frmInstall_lblLeyenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Define y mantiene Vidsoom.com como mi página de inicio y como motor de búsqueda predeterminado.
        ///• Crea un acceso directo en el escritorio..
        /// </summary>
        internal static string frmInstall_lblTipica {
            get {
                return ResourceManager.GetString("frmInstall_lblTipica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación personalizada.
        /// </summary>
        internal static string frmInstall_oPersonalizada {
            get {
                return ResourceManager.GetString("frmInstall_oPersonalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación típica (recomendada).
        /// </summary>
        internal static string frmInstall_oTipica {
            get {
                return ResourceManager.GetString("frmInstall_oTipica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        internal static string frmMain_Archivos {
            get {
                return ResourceManager.GetString("frmMain_Archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string frmMain_btnConfiguracion {
            get {
                return ResourceManager.GetString("frmMain_btnConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string frmMain_btnDescargar {
            get {
                return ResourceManager.GetString("frmMain_btnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Descargas.
        /// </summary>
        internal static string frmMain_btnDescargas {
            get {
                return ResourceManager.GetString("frmMain_btnDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string frmMain_btnEliminar {
            get {
                return ResourceManager.GetString("frmMain_btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa.
        /// </summary>
        internal static string frmMain_btnPausa {
            get {
                return ResourceManager.GetString("frmMain_btnPausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string frmMain_btnPausa_Continuar {
            get {
                return ResourceManager.GetString("frmMain_btnPausa_Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar enlaces.
        /// </summary>
        internal static string frmMain_btnPegar {
            get {
                return ResourceManager.GetString("frmMain_btnPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsualizar.
        /// </summary>
        internal static string frmMain_btnPrevisualizar {
            get {
                return ResourceManager.GetString("frmMain_btnPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir en directorio.
        /// </summary>
        internal static string frmMain_cmAbrir {
            get {
                return ResourceManager.GetString("frmMain_cmAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string frmMain_cmEliminar {
            get {
                return ResourceManager.GetString("frmMain_cmEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa.
        /// </summary>
        internal static string frmMain_cmPausa {
            get {
                return ResourceManager.GetString("frmMain_cmPausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar enlaces.
        /// </summary>
        internal static string frmMain_cmPegar {
            get {
                return ResourceManager.GetString("frmMain_cmPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsualizar.
        /// </summary>
        internal static string frmMain_cmPrevisualizar {
            get {
                return ResourceManager.GetString("frmMain_cmPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar las descargas seleccionadas? Las descargas que no hayan finalizado se borrarán del disco..
        /// </summary>
        internal static string frmMain_Confirm_Eliminar {
            get {
                return ResourceManager.GetString("frmMain_Confirm_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargado.
        /// </summary>
        internal static string frmMain_Descargado {
            get {
                return ResourceManager.GetString("frmMain_Descargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando.
        /// </summary>
        internal static string frmMain_Descargando {
            get {
                return ResourceManager.GetString("frmMain_Descargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargas.
        /// </summary>
        internal static string frmMain_Descargas {
            get {
                return ResourceManager.GetString("frmMain_Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string frmMain_Documentos {
            get {
                return ResourceManager.GetString("frmMain_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string frmMain_Estado {
            get {
                return ResourceManager.GetString("frmMain_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir carpeta de descargas.
        /// </summary>
        internal static string frmMain_mmAbrir {
            get {
                return ResourceManager.GetString("frmMain_mmAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de VidSoom.
        /// </summary>
        internal static string frmMain_mmAcerca {
            get {
                return ResourceManager.GetString("frmMain_mmAcerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string frmMain_mmArchivo {
            get {
                return ResourceManager.GetString("frmMain_mmArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        internal static string frmMain_mmAyuda {
            get {
                return ResourceManager.GetString("frmMain_mmAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string frmMain_mmConfiguracion {
            get {
                return ResourceManager.GetString("frmMain_mmConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición.
        /// </summary>
        internal static string frmMain_mmEdicion {
            get {
                return ResourceManager.GetString("frmMain_mmEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string frmMain_mmEliminar {
            get {
                return ResourceManager.GetString("frmMain_mmEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausar/Reanudar.
        /// </summary>
        internal static string frmMain_mmPausar {
            get {
                return ResourceManager.GetString("frmMain_mmPausar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar enlaces.
        /// </summary>
        internal static string frmMain_mmPegar {
            get {
                return ResourceManager.GetString("frmMain_mmPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsualizar.
        /// </summary>
        internal static string frmMain_mmPrevisualizar {
            get {
                return ResourceManager.GetString("frmMain_mmPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string frmMain_mmSalir {
            get {
                return ResourceManager.GetString("frmMain_mmSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El protocolo de la URL ingresada no es válido..
        /// </summary>
        internal static string frmMain_msgBadProtocol {
            get {
                return ResourceManager.GetString("frmMain_msgBadProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hay una nueva versión de VidSoom disponible! ¿Desea descargarla ahora?.
        /// </summary>
        internal static string frmMain_msgNewVersion {
            get {
                return ResourceManager.GetString("frmMain_msgNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay una nueva versión de VidSoom, ¿Desea descargarla ahora?.
        /// </summary>
        internal static string frmMain_msgUpdate {
            get {
                return ResourceManager.GetString("frmMain_msgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Música.
        /// </summary>
        internal static string frmMain_Musica {
            get {
                return ResourceManager.GetString("frmMain_Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        internal static string frmMain_Origen {
            get {
                return ResourceManager.GetString("frmMain_Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        internal static string frmMain_Peso {
            get {
                return ResourceManager.GetString("frmMain_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programas.
        /// </summary>
        internal static string frmMain_Programas {
            get {
                return ResourceManager.GetString("frmMain_Programas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progreso.
        /// </summary>
        internal static string frmMain_Progreso {
            get {
                return ResourceManager.GetString("frmMain_Progreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando: .
        /// </summary>
        internal static string frmMain_sDescargando {
            get {
                return ResourceManager.GetString("frmMain_sDescargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de sesión: .
        /// </summary>
        internal static string frmMain_sTiempo {
            get {
                return ResourceManager.GetString("frmMain_sTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad total: .
        /// </summary>
        internal static string frmMain_sVelocidad {
            get {
                return ResourceManager.GetString("frmMain_sVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        internal static string frmMain_Titulo {
            get {
                return ResourceManager.GetString("frmMain_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegue aquí los enlaces a descargar....
        /// </summary>
        internal static string frmMain_tURL {
            get {
                return ResourceManager.GetString("frmMain_tURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad.
        /// </summary>
        internal static string frmMain_Velocidad {
            get {
                return ResourceManager.GetString("frmMain_Velocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string frmMain_Videos {
            get {
                return ResourceManager.GetString("frmMain_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string frmQuality_btnCancelar {
            get {
                return ResourceManager.GetString("frmQuality_btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string frmQuality_btnDescargar {
            get {
                return ResourceManager.GetString("frmQuality_btnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la calidad del video.
        /// </summary>
        internal static string frmQuality_frmQuality {
            get {
                return ResourceManager.GetString("frmQuality_frmQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una calidad..
        /// </summary>
        internal static string frmQuality_msgSeleccione {
            get {
                return ResourceManager.GetString("frmQuality_msgSeleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        internal static string General_Ended {
            get {
                return ResourceManager.GetString("General_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string General_EndedWithError {
            get {
                return ResourceManager.GetString("General_EndedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita preparse.
        /// </summary>
        internal static string General_NeedToPrepare {
            get {
                return ResourceManager.GetString("General_NeedToPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausado.
        /// </summary>
        internal static string General_Paused {
            get {
                return ResourceManager.GetString("General_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausando.
        /// </summary>
        internal static string General_Pausing {
            get {
                return ResourceManager.GetString("General_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparado.
        /// </summary>
        internal static string General_Prepared {
            get {
                return ResourceManager.GetString("General_Prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando.
        /// </summary>
        internal static string General_Preparing {
            get {
                return ResourceManager.GetString("General_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando reconexión.
        /// </summary>
        internal static string General_WaitingForReconnect {
            get {
                return ResourceManager.GetString("General_WaitingForReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando.
        /// </summary>
        internal static string General_Working {
            get {
                return ResourceManager.GetString("General_Working", resourceCulture);
            }
        }
    }
}
